

import { AppSettings } from './types';

export const DEFAULT_SETTINGS: AppSettings = {
  language: 'zh_cn',
  apiMode: 'openai',
  baseUrl: 'https://api.openai.com',
  apiKey: '',
  model: 'gpt-4o',
  fontFamily: "'Crimson Text', 'Noto Serif TC', serif",
  customFontUrl: '',
};

export const IRREGULAR_VERBS: Record<string, string> = {
  "was": "be", "were": "be", "been": "be", "am": "be", "is": "be", "are": "be", "'s": "be", "'re": "be", "'m": "be",
  "had": "have", "has": "have", "having": "have", "'ve": "have", "'d": "have",
  "did": "do", "done": "do", "does": "do", "doing": "do",
  "went": "go", "gone": "go", "goes": "go", "going": "go",
  "said": "say", "made": "make", "took": "take", "taken": "take",
  "came": "come", "saw": "see", "seen": "see", "knew": "know", "known": "know",
  "got": "get", "gotten": "get", "gave": "give", "given": "give",
  "found": "find", "told": "tell", "became": "become", "left": "leave",
  "thought": "think", "bought": "buy", "brought": "bring", "wrote": "write", "written": "write",
  "sat": "sit", "stood": "stand", "lost": "lose", "paid": "pay", "met": "meet",
  "led": "lead", "understood": "understand", "spoke": "speak", "spoken": "speak",
  "read": "read", "spent": "spend", "grew": "grow", "grown": "grow",
  "opened": "open", "closed": "close", "stopped": "stop", "tried": "try",
  "won": "win", "taught": "teach", "sold": "sell", "caught": "catch", "swam": "swim", "swum": "swim",
  "began": "begin", "begun": "begin", "drank": "drink", "drunk": "drink", "sang": "sing", "sung": "sing",
  "ran": "run", "ate": "eat", "eaten": "eat", "fell": "fall", "fallen": "fall", "felt": "feel", "kept": "keep",
  "slept": "sleep", "swept": "sweep", "wept": "weep", "built": "build", "lent": "lend", "sent": "send",
  "meant": "mean", "dreamt": "dream", "learnt": "learn", "burnt": "burn",
  "cut": "cut", "put": "put", "set": "set", "hit": "hit", "let": "let", "hurt": "hurt", "cost": "cost",
  "shut": "shut", "quit": "quit", "spread": "spread", "broadcast": "broadcast"
};

export const TRANSLATIONS = {
  en: {
    appTitle: "Just Want to Read Novels",
    settings: "Settings",
    tabStaging: "Staging Area",
    tabPdf: "PDF Preview",
    exportPdf: "Export PDF",
    vocabImportTitle: "1. Import Vocabulary (Grading DB)",
    batchUpload: "Batch Upload",
    clearCache: "Clear Cache",
    level: "Level",
    file: "File",
    orUrl: "or URL",
    empty: "Empty",
    importNovelTitle: "2. Import Novel (.txt)",
    dragDrop: "Drag & drop .txt file or click to upload",
    novelLoaded: "Novel loaded successfully",
    importFirst: "Please import vocabulary first to unlock",
    current: "Current",
    clearNovel: "Clear Novel",
    directory: "Directory",
    totalChapters: "Total {count} Chapters",
    segments: "segments",
    translated: "Translated",
    phase1: "Phase 1: Translate All",
    phase2: "Phase 2: Generate Notes ({count})",
    selectAll: "Select All",
    waitTrans: "Wait trans.",
    addPdf: "Add PDF",
    genNotes: "Gen Notes",
    done: "Done",
    processing: "...",
    pdfEmpty: "PDF Preview Area. Add segments from the list to see them here.",
    pageBreak: "--- Page Break ---",
    saveChanges: "Save Changes",
    apiConfig: "API Configuration",
    appearance: "Appearance & PDF",
    providerMode: "Provider Mode",
    baseUrl: "Base URL",
    apiKey: "API Key",
    modelName: "Model Name",
    fontFamily: "Font Family (PDF)",
    language: "Interface Language",
    fetchModels: "Fetch Models",
    fetching: "Fetching...",
    fetchError: "Fetch failed",
    enterManually: "Enter manually",
    apiMissing: "API Key is missing. Please configure it in Settings.",
    taskCompleted: "Task Completed",
    taskTime: "Time elapsed: {seconds}s",
    loadBuiltIn: "Load Built-in Library",
    loadSuccess: "Default vocabulary loaded successfully.",
    loadFail: "Failed to load default vocabulary.",
    projectManage: "Project Management",
    exportProject: "Export Project Backup (.json)",
    importProject: "Import Project Backup",
    projectLoaded: "Project imported successfully!",
    restoreBackup: "Or restore from Project Backup (.json)",
    or: "OR",
    guideTitle: "User Guide",
    guideStep1: "Import Vocabulary",
    guideDesc1: "Load your vocabulary grading standard (or use the built-in library). The system uses this to identify difficult words.",
    guideStep2: "Import Novel",
    guideDesc2: "Upload a Chinese novel in .txt format. The system will automatically parse chapters.",
    guideStep3: "Translate",
    guideDesc3: "Click 'Translate All' to use AI for high-quality translation.",
    guideStep4: "Generate Notes",
    guideDesc4: "Select paragraphs and click 'Gen Notes'. AI extracts difficult words and adds annotations.",
    guideStep5: "Export PDF",
    guideDesc5: "Add processed content to the PDF Preview area and export your study material.",
    gotIt: "Got it",
    clearPdf: "Clear",
    confirmClearPdf: "Clear all PDF content? This cannot be undone.",
  },
  zh_cn: {
    appTitle: "只想看小说",
    settings: "设置",
    tabStaging: "工作台",
    tabPdf: "PDF 预览",
    exportPdf: "导出 PDF",
    vocabImportTitle: "1. 导入词汇库 (分级标准)",
    batchUpload: "批量上传",
    clearCache: "清除缓存",
    level: "等级",
    file: "文件",
    orUrl: "或 URL",
    empty: "空",
    importNovelTitle: "2. 导入小说 (.txt)",
    dragDrop: "拖拽 .txt 文件或点击上传",
    novelLoaded: "小说加载成功",
    importFirst: "请先导入词汇库以解锁",
    current: "当前",
    clearNovel: "清除小说",
    directory: "目录",
    totalChapters: "共 {count} 章",
    segments: "段",
    translated: "已翻译",
    phase1: "第一阶段：全文翻译",
    phase2: "第二阶段：生成笔记 ({count})",
    selectAll: "全选",
    waitTrans: "待翻译",
    addPdf: "加入 PDF",
    genNotes: "生成笔记",
    done: "完成",
    processing: "处理中",
    pdfEmpty: "PDF 预览区。请从左侧列表添加内容。",
    pageBreak: "--- 分页符 ---",
    saveChanges: "保存设置",
    apiConfig: "API 配置",
    appearance: "外观与 PDF",
    providerMode: "API 模式",
    baseUrl: "接口地址 (Base URL)",
    apiKey: "API 密钥",
    modelName: "模型名称",
    fontFamily: "PDF 字体",
    language: "界面语言",
    fetchModels: "获取模型列表",
    fetching: "获取中...",
    fetchError: "获取失败",
    enterManually: "手动输入",
    apiMissing: "尚未配置 API Key。请在设置中输入。",
    taskCompleted: "任务已完成",
    taskTime: "总耗时: {seconds} 秒",
    loadBuiltIn: "加载默认库",
    loadSuccess: "默认词汇库加载成功。",
    loadFail: "默认词汇库加载失败。",
    projectManage: "项目管理",
    exportProject: "导出项目备份 (.json)",
    importProject: "导入项目备份",
    projectLoaded: "项目导入成功！",
    restoreBackup: "或从项目备份恢复 (.json)",
    or: "或",
    guideTitle: "使用指南",
    guideStep1: "导入词汇库",
    guideDesc1: "加载分级词汇表（或直接加载默认库）。系统将依据此标准判断生词难度。",
    guideStep2: "导入小说",
    guideDesc2: "上传 .txt 格式的中文小说文件。系统会自动解析章节目录。",
    guideStep3: "AI 翻译",
    guideDesc3: "点击“全文翻译”，AI 将为章节生成高质量的中英对照文本。",
    guideStep4: "生成笔记",
    guideDesc4: "勾选段落并点击“生成笔记”，AI 会提取难词并提供释义。",
    guideStep5: "导出 PDF",
    guideDesc5: "将处理好的内容“加入 PDF”预览区，最后导出精美的学习讲义。",
    gotIt: "知道了",
    clearPdf: "清空",
    confirmClearPdf: "确定要清空 PDF 预览区的内容吗？",
  },
  zh_tw: {
    appTitle: "只想看小說",
    settings: "設定",
    tabStaging: "工作台",
    tabPdf: "PDF 預覽",
    exportPdf: "匯出 PDF",
    vocabImportTitle: "1. 匯入詞彙庫 (分級標準)",
    batchUpload: "批量上傳",
    clearCache: "清除緩存",
    level: "等級",
    file: "文件",
    orUrl: "或 URL",
    empty: "空",
    importNovelTitle: "2. 匯入小說 (.txt)",
    dragDrop: "拖拽 .txt 文件或點擊上傳",
    novelLoaded: "小說加載成功",
    importFirst: "請先匯入詞彙庫以解鎖",
    current: "當前",
    clearNovel: "清除小說",
    directory: "目錄",
    totalChapters: "共 {count} 章",
    segments: "段",
    translated: "已翻譯",
    phase1: "第一階段：全文翻譯",
    phase2: "第二階段：生成筆記 ({count})",
    selectAll: "全選",
    waitTrans: "待翻譯",
    addPdf: "加入 PDF",
    genNotes: "生成筆記",
    done: "完成",
    processing: "處理中",
    pdfEmpty: "PDF 預覽區。請從左側列表添加內容。",
    pageBreak: "--- 分頁符 ---",
    saveChanges: "保存設定",
    apiConfig: "API 配置",
    appearance: "外觀與 PDF",
    providerMode: "API 模式",
    baseUrl: "接口地址 (Base URL)",
    apiKey: "API 金鑰",
    modelName: "模型名稱",
    fontFamily: "PDF 字體",
    language: "介面語言",
    fetchModels: "獲取模型列表",
    fetching: "獲取中...",
    fetchError: "獲取失敗",
    enterManually: "手動輸入",
    apiMissing: "尚未配置 API Key。請在設定中輸入。",
    taskCompleted: "任務已完成",
    taskTime: "總耗時: {seconds} 秒",
    loadBuiltIn: "加載默認庫",
    loadSuccess: "默認詞彙庫加載成功。",
    loadFail: "默認詞彙庫加載失敗。",
    projectManage: "項目管理",
    exportProject: "匯出項目備份 (.json)",
    importProject: "匯入項目備份",
    projectLoaded: "項目匯入成功！",
    restoreBackup: "或從項目備份恢復 (.json)",
    or: "或",
    guideTitle: "使用指南",
    guideStep1: "匯入詞彙庫",
    guideDesc1: "加載分級詞彙表（或直接加載默認庫）。系統將依據此標準判斷生詞難度。",
    guideStep2: "匯入小說",
    guideDesc2: "上傳 .txt 格式的中文小說文件。系統會自動解析章節目錄。",
    guideStep3: "AI 翻譯",
    guideDesc3: "點擊“全文翻譯”，AI 將為章節生成高質量的中英對照文本。",
    guideStep4: "生成筆記",
    guideDesc4: "勾選段落並點擊“生成筆記”，AI 會提取難詞並提供釋義。",
    guideStep5: "匯出 PDF",
    guideDesc5: "將處理好的內容“加入 PDF”預覽區，最後匯出精美的學習講義。",
    gotIt: "知道了",
    clearPdf: "清空",
    confirmClearPdf: "確定要清空 PDF 預覽區的內容嗎？",
  }
};